name: ""
relative_permalinks: true
markdown: kramdown
highlighter: pygments
# paginate: 12
# paginate_path: "blog/page:num"

author :
  name : David Kim
  email : betterandhigher@gmail.com
  github : BetterandHigher
  twitter : 
  feedburner : 

production_url : 
BASE_PATH : false
ASSET_PATH: false

# Google analytics
analytics:
  provider: google
  google:
    tracking_id: 
  getclicky:
    site_id:

comments:
  provider : 
  disqus:
    short_name: 
